# Generated by Django 3.2.9 on 2021-11-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_auto_20211129_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user'), (None, None)], max_length=8, verbose_name='등급'),
        ),
    ]
