# Generated by Django 3.2.9 on 2021-11-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0005_alter_fcuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=8, verbose_name='등급'),
        ),
    ]
